=== ivcp1415/LMSGI_DTD/esdeveniments.dtd
<!-- esdeveniments ha de tenir més d'un element -->
<!ELEMENT esdeveniments (esdeveniment+)>

<!-- esdeveniment ha de tenir com a mínim un grup i una data -->
<!ELEMENT esdeveniment (grup+, lloc, data+, entrada)>

<!ELEMENT grup (#PCDATA)>
<!ELEMENT lloc (#PCDATA)>
<!ELEMENT data (#PCDATA)>
<!ELEMENT entrada (#PCDATA)>

<!-- entrada pot ser gratuita i té per defecte l'opció "no" -->
<!ATTLIST entrada gratuita (si|no) "no">

=== ivcp1415/LMSGI_DTD/esdeveniments.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE esdeveniments SYSTEM "esdeveniments.dtd">
<esdeveniment>
    <esdeveniment>
        <grup></grup>
        <lloc></lloc>
        <data></data>
        <entrada gratuita="no"></entrada>
    </esdeveniment>
    <esdeveniment>
        <grup></grup>
        <lloc></lloc>
        <data></data>
        <entrada gratuita="si"></entrada>
    </esdeveniment>
    <esdeveniment>
    </esdeveniment>
        <grup></grup>
        <lloc></lloc>
        <data></data>
        <entrada gratuita="no"></entrada>
    </esdeveniment>
</esdeveniment>
